server:
  port: 7766
  servlet:
    # 不要修改context-path
    context-path: /

kafka:
  config:
    # 如果不存在default集群，启动的时候默认会把这个加载进来(如果这里配置集群地址了)，如果已经存在，则不加载
    # kafka broker地址，多个以逗号分隔，不是必须在这里配置，也可以启动之后，在页面上添加集群信息
    bootstrap-server:
    # 集群其它属性配置
    properties:
#      request.timeout.ms: 5000

spring:
  application:
    name: kafka-console-ui
  # h2 database
  datasource:
    url: jdbc:h2:file:${data.dir:${user.dir}}/data/db/kafka-console
#    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: kafka
    password: 1234567890
    schema: classpath:db/schema-h2.sql
#    data: classpath:db/data-h2.sqldata.dir
    initialization-mode: always
  h2:
    console:
      enabled: true
#      settings:
#        web-allow-others: true

logging:
  home: ./

# 基于scram方案的acl，这里会记录创建的用户密码等信息，定时扫描，如果集群中已经不存在这些用户，就把这些信息从db中清除掉
cron:
#  clear-dirty-user: 0 * * * * ?
  clear-dirty-user: 0 0 1 * * ?
